### ISSUE TITLE
Hacktober Feature Request: Document how to run website locally

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#10]
### Describe the feature

- Instructions are added to the readme for how to run the website locally.

### Advantages

- Helps others to test their changes.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] The readme instructions can be followed to run the website locally.

**Comment by rajeevbhat27** [comment]
Hey..looks like this has been completed already.

**Comment by wordshaker** [comment]
You are quite right. Sorry about that. I will close this issue.
