### ISSUE TITLE
Hacktober Feature Request: Add tabbing behaviour to text on the Speak Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#11]
### Describe the feature

- To be able to tab through all headers and paragraph sections

### Advantages

- Improves the accessibility of the website

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Can tab through the text sections of the Speak page.

**Comment by Aliecake** [comment]
I'd like to work on this

**Comment by wordshaker** [comment]
It's all yours @Aliecake

**Comment by wordshaker** [comment]
Completed by @Aliecake
