### ISSUE TITLE
Hacktober Feature Request: Add tabbing behaviour to text on the Code Of Conduct Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#12]
### Describe the feature

- To be able to tab through all headers and paragraph sections

### Advantages

- Improves the accessibility of the website

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Can tab through the text sections of the Code of Conduct page.

**Comment by jonasvag** [comment]
https://github.com/dotnetnotts/dotnetnotts-web/pull/48
