### ISSUE TITLE
Hacktober Feature Request: Add Content To Speaker Info Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#13]
### Description Of Feature

* Add content to the Speaker Info page.

Content can be found here: https://dotnetnotts.co/#!/speakerinfo

### Advantages

* The Speaker Info Page shares information that prospective speakers may need.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] The content of https://dotnetnotts.co/#!/speakerinfo shows on the Speaker Info page for the new site
- [ ] The formatting matches the previous Speaker Info page.

**Comment by mosoftwareenterprises** [comment]
Can I take this @wordshaker ?

**Comment by wordshaker** [comment]
Certainly 😄
