### ISSUE TITLE
Hacktober Feature Request: Make website responsive

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#15]
### Describe the feature

- The website is useable and attractive on mobile and tablet views

### Advantages

- The website can be used and accessed on any device

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Website works on tablet
- [ ] Website works on mobile

**Comment by CilgaIscan** [comment]
I would like to work on this project for Hacktober2020, @wordshaker

**Comment by pjgpetecodes** [comment]
Sounds good to me @CilgaIscan ... Consider yourself assigned!

This one may require more than one person, so do please put your hand up if you'd like to help!

**Comment by CilgaIscan** [comment]
Noticed the project is written in .NET which I am not familiar with. Due to this, I unassigned myself.
