### ISSUE TITLE
Hacktober Feature Request: Add Sponsor images to the home page.

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#16]
### Describe the feature

Sponsor logos are added to the bottom of the homepage of the website and links are opened in a new tab.

- The ____ logo is linked to ____

### Advantages

- Lets people know about our awesome sponsors!

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Sponsor images are at the bottom of the .NET Notts homepage
- [ ] ___ logo is linked to ____

**Comment by rajeevbhat27** [comment]
Hi.. I wanna take this up in Hacktoberfest.

**Comment by wordshaker** [comment]
Hey @pjgpetecodes, where can @rajeevbhat27 find images of the sponsor logos?

**Comment by rajeevbhat27** [comment]
I am gonna need those sponsor logos and links. Thanks

**Comment by pjgpetecodes** [comment]
Hey @rajeevbhat27 ... These should be in the `wwwroot/images/sponsors` folder now...

**Comment by wordshaker** [comment]
Completed by @rajeevbhat27
