### ISSUE TITLE
Feature Request: Add Speaker information from Sessionise to website

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#185]
### Describe the feature

Add the Speakers Wall from Sessionize to display our past and planned speakers

https://sessionize.com/api/v2/eq1opc2o/view/SpeakerWall

### Advantages

- Shows who has spoken and is going to speak at .NET Notts

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] A speakers page displays the information from Sessionise

![image](https://user-images.githubusercontent.com/13496774/192475637-d7413d8a-f13b-4b14-a2c3-09f3f786f7ed.png)
![image](https://user-images.githubusercontent.com/13496774/192475703-5ecd7840-7ff5-488d-b21b-06a970db4213.png)

**Comment by rebiiin** [comment]
I tried to add Speakers into Speaker Information page all Speakers were showed up but only popups not working
would you mind change API format in Sessionize account from **Embed Styled Html**  to **json** format ? I'll handle it.
<img width="1281" alt="Capture" src="https://user-images.githubusercontent.com/3890058/192978804-1d7daf0d-9472-4df1-9f51-2c57a142650c.PNG">

**Comment by wordshaker** [comment]
I've changed the format on the sessionize UI https://sessionize.com/api/v2/eq1opc2o/view/SpeakerWall 
Thanks!

**Comment by rebiiin** [comment]
Thanks Jessica, I will work on it.
