### ISSUE TITLE
Hacktober Feature Request: Add Gallery of Speakers Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#19]
### Describe the feature

- A page which has a grid of images of past speakers
- Images could have speakers social links

### Advantages

- An easy place to see and find out about all our great past speakers

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Page with a gallery of speaker images
- [ ] The page is responsive and the grid works on desktop, tablet, and mobile

**Comment by Divyanshwick** [comment]
I want to contribute to this issue

**Comment by pjgpetecodes** [comment]
Sounds great @Divyanshwick! Consider yourself assigned!

**Comment by wordshaker** [comment]
Hey @pjgpetecodes, please can you add somewhere that the contributor can access the images?

**Comment by pjgpetecodes** [comment]
Yup... I'll go and collect a bunch of photos and update the issue once I've sorted them!

**Comment by pjgpetecodes** [comment]
I've now created a pull request containing the speaker photos... Once it's approved, I'll update this Issue.

**Comment by wordshaker** [comment]
@Divyanshwick - the photos are now available in the repo 😄
