### ISSUE TITLE
Hacktober Feature Request: Add Content To Code of Conduct Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#2]
### Description Of Feature

* Add the code of conduct for .NET Notts to the Code of Conduct page.

Content can be found here: https://dotnetnotts.co/#!/codeofconduct

### Advantages

* The Code of Conduct ensures that the .NET Notts environment runs in a way that is safe and welcoming to all those attending. It informs attendees what to do when they feel unsafe or uncomfortable and what actions the event will be taken when the CoC is broken

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] The content of https://dotnetnotts.co/#!/codeofconduct shows on the Code Of Conduct page for the new site
- [ ] The formatting matches the previous Code of Conduct

**Comment by mosoftwareenterprises** [comment]
I would like to pick this issue up if I could.

**Comment by Riya-code** [comment]
@wordshaker can I take it?

**Comment by wordshaker** [comment]
Hi @mosoftwareenterprises requested the issue first so it will go to them.

**Comment by mosoftwareenterprises** [comment]
@wordshaker do I need to do anything else with this? Not sure what's next in the process.
Thanks
Mark

**Comment by wordshaker** [comment]
Nope you are all done 😄 I will close this issue now. Thanks for your contribution.
