### ISSUE TITLE
Hacktober Feature Request: Add footer

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#20]
### Describe the feature

- Footer is added in the .NET Notts colour : #05bd9e
- Any text on the Footer is white

### Advantages

N/A

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Footer is displayed on all pages of the website.

**Comment by rajeevbhat27** [comment]
Hello...I want to take this up for Hactoberfest.

**Comment by Divyanshwick** [comment]
I want to contribute to this issue

**Comment by pjgpetecodes** [comment]
Ooo... As @rajeevbhat27 was first, I'll go ahead and assign it to Rajeev if that's ok @Divyanshwick?

Feel free to comment back if you decide between you to switch!

**Comment by rajeevbhat27** [comment]
Hello, which all social media links do you need in footer ? Please provide links for that.
Thanks

**Comment by wordshaker** [comment]
- Twitter: https://twitter.com/dotnetnotts
- LinkedIn: https://www.linkedin.com/company/dotnet-notts
- Meetup: https://www.meetup.com/dotnetnotts

and yes, you can use font-awesome

**Comment by rajeevbhat27** [comment]
hey @wordshaker  for some reason import of font awesome is not working in  app.css. Could you add fontawesome to the project?
