### ISSUE TITLE
Hacktober Feature Request: Add social media links to the footer

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#21]
### Describe the feature

**To be done after the issue #20 is completed**

Links to our social media pages are added to the footer 

### Advantages

N/A

### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

**Links to our social media pages are added to the footer** 

- [ ] Twitter https://twitter.com/dotnetnotts

- [ ] Meetup https://www.meetup.com/dotnetnotts

- [ ] LinkedIn https://www.linkedin.com/company/dotnet-notts

- [ ] Github https://github.com/dotnetnotts

**Comment by Haniket** [comment]
I want to work on this........

**Comment by Divyanshwick** [comment]
I want to work on this issue

**Comment by Haniket** [comment]
@wordshaker how to run the application on my local system....plz help

**Comment by pjgpetecodes** [comment]
> @wordshaker how to run the application on my local system....plz help
> 

You should be able to clone the repo, then either open and run the app in Visual Studio 2019 or from the CLI with `dotnet run`.

You'll also need the latest .NET Core of course.

**Comment by wordshaker** [comment]
I will add instructions to the Readme today
