### ISSUE TITLE
Hacktober Feature Request: Create Contact Us Page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#22]
### Describe the feature

- Contact Us Page is added to the website and linked on the navigation bar
- Contains information about the co-organisers Pete and Jess
- Has links for how to contact them by email.

### Advantages

- If anyone needs to get in touch they will be able to find out how to on the website.

### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Add Contact Us Page to Nav Bar

- [ ] New Page added with details of how to contact Pete and Jess

**Comment by Haniket** [comment]
hi there,I am new to open source and looking forward to participate in hacktoberfest 2020.Can I work on it

**Comment by wordshaker** [comment]
Yeah sure 👍🏼 Let us know if you need any assistance

**Comment by Haniket** [comment]
mam link on contribution.md  file is showing 404 errror........if you can tell how to make contribution will be helpfull......

**Comment by Haniket** [comment]
@wordshaker what are the details I have to put in the contact us page means I don't have information about Pete and Jess to put in the contact us page

**Comment by wordshaker** [comment]
Ah yes, sorry

### General Meetup contact details

You can contact the organisers on any of the meetups social media sites. Both Pete and Jessica have access.

Twitter: https://twitter.com/dotnetnotts
Meetup: https://www.meetup.com/dotnetnotts
LinkedIn: https://www.linkedin.com/company/dotnet-notts

### Organisers

**Pete Gallagher** 

Pete is a Freelance Programmer, Microsoft Azure MVP, Pluralsight Author, Public Speaker, and STEM Ambassador. He is the co-organiser of multiple meetups including Notts IoT, Dot Net Notts, and Notts Dev Workshop

Email: pete@pjgcreations.co.uk
Twitter: https://twitter.com/pete_codes
Website: https://www.petecodes.co.uk/

**Jessica White**

Jessica is a developer, international speaker, and MVP in Developer Technologies. She founded Women In Tech Nottingham, which she handed over to new organisers in 2017, and co-organises the DDD East Midland Conference.

Email: me@jesswhite.co.uk
Twitter: https://twitter.com/JessPWhite
Website: https://jesswhite.co.uk/

**Comment by wordshaker** [comment]
Feel free to put this information on the page in any way you like. Let me know if you want any images.

**Comment by Haniket** [comment]
@wordshaker can you please give me 1 photo each of jess and pete....adding the photo will be give the page a great look.....

**Comment by Haniket** [comment]
@wordshaker do I have to make footer also on contact us page ......

**Comment by wordshaker** [comment]
No you don't 😄 I'll raise another issue for adding a footer to all pages

**Comment by Haniket** [comment]
> No you don't 😄 I'll raise another issue for adding a footer to all pages

okk

> @wordshaker can you please give me 1 photo each of jess and pete....adding the photo will be give the page a great look.....

@wordshaker mam what about images....

**Comment by wordshaker** [comment]
**Pete**
![image](https://user-images.githubusercontent.com/13496774/94461869-9923d180-01b2-11eb-8fc2-e7aef6c75a5e.png)

https://res.cloudinary.com/dsfcrod4r/image/upload/v1601311468/.NET%20Notts/Pete_ashxih.jpg

**Jessica**

![image](https://user-images.githubusercontent.com/13496774/94461926-ae006500-01b2-11eb-92df-1289b8ccd032.png)

https://res.cloudinary.com/dsfcrod4r/image/upload/v1601311587/.NET%20Notts/Jess_a9lajy.jpg

**Comment by mallick370** [comment]
Hello, I am new to hacktober fest and I am an UI/UX Designer, I will like to design the UI of the website. Can I make contribution in this manner?

**Comment by wordshaker** [comment]
Hi @mallick370 

We would love to see your designs and you can certainly submit some.

You could redesign any page and, as discussed in issue #28, to get your PR for Hacktoberfest add a link to your designs or the images to the repositories readme. 

Let me know if we can help in any way

**Comment by Haniket** [comment]
@wordshaker  as I have completed the task plz add "hacktoberfest-accepted" label to so that it can be counted in hacktoberfest as mentioned on there website.....

**Comment by wordshaker** [comment]
Completed by @Haniket
