### ISSUE TITLE
Bug: The "Contribution Guidelines" link is broken in the README.md file

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnetnotts/dotnetnotts-web#23]
### Describe the bug

- The Contributing Guidelines link in the repo README.md file is broken. 
- It currently returns a 404 Page.
- The link is pointing to `./github/contributing.md`, which doesn't exist.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to [README.md](README.md#contributing)
2. Click Contributing Link

**Reproduces how often:**

100% of the time.

**Expected behaviour**

Should take the user to `.github/contributing.md`.

**Screenshots**

![image](https://user-images.githubusercontent.com/7139618/94166106-d6225800-fe82-11ea-99a1-65c4b2c7f8da.png)
![image](https://user-images.githubusercontent.com/7139618/94166068-cdca1d00-fe82-11ea-9d42-80fdcbcd74c6.png)

**Comment by HarshalGoyal** [comment]
@pjgpetecodes i just fixed it and created the PR kindly check it

**Comment by soulhunter10737** [comment]
I would like to take this

**Comment by pjgpetecodes** [comment]
Awwww... Sorry @soulhunter10737 ... It's been done already!

**Comment by soulhunter10737** [comment]
@pjgpetecodes  Thanks for telling! Better luck next time :)
