### ISSUE TITLE
Bug: Update Contents Section in the Readme

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#26]
### Describe the bug

The Contents section in the [Readme is currently incomplete](https://github.com/dotnetnotts/dotnetnotts-web/blob/main/README.md)

**To Reproduce**

Visible from [the main repository page](https://github.com/dotnetnotts/dotnetnotts-web/) and [here]](https://github.com/dotnetnotts/dotnetnotts-web/blob/main/README.md)

**Reproduces how often:**

Always

**Expected behaviour**

There should be a link per section of the Readme in the contents

**Screenshots**

N/A

**Comment by ShubhamSood1406** [comment]
Hey, @wordshaker whats the actual bug as I can see in Readme.md file that there is a Section for Branding and Contributing in Contents.

**Comment by wordshaker** [comment]
![image](https://user-images.githubusercontent.com/13496774/94346092-4ddab900-0022-11eb-86e9-51a225ba5cf8.png)

The `Local Development` and subheadings for this section are missing from the contents section

**Comment by ShubhamSood1406** [comment]
Okay, I will try to fix it and will add Local Development and its sub-heading and Build Tool to Contents section. Can you assign me this issue?

**Comment by ShubhamSood1406** [comment]
Is it fine that I will send PR on October 1st?

**Comment by wordshaker** [comment]
Yes that's fine. We are expecting these issues to be dealt with over October.
