### ISSUE TITLE
Feature Request: Upgrade to .NET 8

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#270]
### Describe the feature

- Upgrade to use .NET 8

### Advantages

- I wanna be the very best

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Upgrade to use .NET 8

**Comment by wordshaker** [comment]
@gyro2009 - wanna give it a stab?

**Comment by gyro2009** [comment]
Yes please! Leave it with me
