### ISSUE TITLE
Hacktober Feature Request: Design Homepage

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#28]
### Describe the feature

- Design the homepage
- Add a link to the readme branding section

### Advantages

- We'll have an idea what the homepage should look like

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Must match the branding outlined in the readme

**Comment by rach-m** [comment]
Happy to work on this! Would love more information regarding any thoughts/requirements you may have in mind

**Comment by RitikaShrestha-me** [comment]
Can I work on this?

**Comment by wordshaker** [comment]
Please do @RitikaShrestha-me  😄 Let us know if you need any further instruction

**Comment by RitikaShrestha-me** [comment]
Is there any details on what all is to be kept in the Homepage?

**Comment by wordshaker** [comment]
You have free reign. Whatever you think a person would want to see on the homepage if they wanted to learn more about the meetup
