### ISSUE TITLE
Hacktober Feature Request: Add UI Tests

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#30]
### Describe the feature

- Using a framework of your choice, add some initial front end tests

### Advantages

- Ensures we don't break the front end with our changes

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Front end tests run and pass
- [ ] How to run the front end tests is documented in the readme

**Comment by LukeBillo** [comment]
Hey! I'll take a look into doing this.

Could you elaborate a little into what you want for 'front end' tests? Not sure if you mean acceptance level (i.e. Selenium) or something like [bUnit](https://github.com/egil/bUnit)? I can do both if you like, but if so I'll probably do it as two separate PRs if that's alright.

**Comment by wordshaker** [comment]
Hey @LukeBillo bUnit should be fine, but if you want to do both, feel free 😄 Two PRs if fine as well

**Comment by wordshaker** [comment]
Completed by @LukeBillo

**Comment by LukeBillo** [comment]
Hey @wordshaker - just as a note, I just realised I never added this to the GitHub workflow. Did you want me to raise a quick PR later today to add it in?

**Comment by wordshaker** [comment]
@LukeBillo that would be awesome if you don't mind
