### ISSUE TITLE
Hacktober Feature Request: Add .NET Links to Learn .NET page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#37]
### Describe the feature

Add the following links under a Learn .NET header:

- [ ] Microsoft Learn .NET Page - https://dotnet.microsoft.com/learn

- [ ] First Steps with C# Learning Path - https://docs.microsoft.com/en-gb/learn/paths/csharp-first-steps/?WT.mc_id=cloudskills-stream-ajack

- [ ] .NET Docs - https://docs.microsoft.com/en-gb/dotnet/?WT.mc_id=cloudskills-stream-ajack

- [ ] ASP.NET Docs - https://docs.microsoft.com/en-gb/aspnet/core/?view=aspnetcore-3.1&WT.mc_id=cloudskills-stream-ajack

- [ ] Work with data in C# - https://docs.microsoft.com/en-gb/learn/paths/csharp-data/?WT.mc_id=cloudskills-stream-ajack

### Advantages

- Helps those new to .NET find resources

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Listed linked have been added to the Learn .NET page

**Comment by BatoolMM** [comment]
Hi @wordshaker , can you assign it to me, please?

**Comment by wordshaker** [comment]
It's all yours 😄
