### ISSUE TITLE
Hacktober Feature Request: Add  Azure Links to Learn page

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#38]
### Describe the feature

Add the following links under a Learn Azureheader:

- [ ] Azure documentation - https://docs.microsoft.com/en-gb/azure/?product=featured#languages-and-tools&WT.mc_id=cloudskills-stream-ajack

- [ ] Quickstart: Create a function in Azure that responds to HTTP requests - https://docs.microsoft.com/en-gb/azure/azure-functions/functions-create-first-azure-function-azure-cli?pivots=programming-language-csharp&tabs=bash%2Cbrowser&WT.mc_id=cloudskills-stream-ajack

### Advantages

- Helps those new to Azure find resources

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Listed linked have been added to the Learn page

**Comment by kyebrowning** [comment]
Would I be able to take this one?

**Comment by ReoCorreia** [comment]
I like to this project

**Comment by wordshaker** [comment]
It's all yours @kyebrowning

**Comment by kyebrowning** [comment]
@wordshaker looks like this has already been done with a previous branch. Would you still like me to do it?
