### ISSUE TITLE
Hacktober Feature Request: Rename Learn .NET page and link

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#39]
### Describe the feature

- Rename Learn .NET page to Learn
- Rename Learn .NET link to Learn

### Advantages

- Means we can add resources for learning Azure as well as .NET in this page

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Both link in navigation bar and page are called "Learn"

**Comment by Augilar** [comment]
@wordshaker Can I do this ?

**Comment by wordshaker** [comment]
Thank you for your contribution @Augilar
