### ISSUE TITLE
Hacktober Feature Request: Upload speaker images

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnetnotts/dotnetnotts-web#42]
### Describe the feature

- We need a set of Speaker Images from Previous Events adding to the site to use on the Speakers Page

### Advantages

- We can create a page showing images of previous speakers

#### Acceptance Criteria

- A folder created in the wwwroot/images director named speakers.
- Various images of previous speakers
- Naming Convention - firstname_lastname_imagenumber.png

**Comment by baspalinckx** [comment]
I wouldn't mind helping, but do you have these images so that I can place them on the site? If so, please assign me!

**Comment by pjgpetecodes** [comment]
Howdy @baspalinckx ... I've sorted this one... But thanks for the offer!
