### ISSUE TITLE
Hacktober Feature Request: Add tabbing behavior to Navigation

### ISSUE THREAD

**Issue by Aliecake** [dotnetnotts/dotnetnotts-web#54]
### Describe the feature

- Ability to tab through the navigation first

### Advantages

- Improving accessibility.

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Can tab through navigation

**Comment by Aliecake** [comment]
I'd like to work on this

**Comment by wordshaker** [comment]
Done by @Aliecake
