### ISSUE TITLE
Hacktober Feature Request: Allow application to use any major version of .NET Core 3.1

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnetnotts/dotnetnotts-web#61]
### Describe the feature

Currently the site is bound to .NET Core 3.1.401.

We'd like to allow any major version of .NET Core 3.1 to be used.

The main issue is with the GitHub Actions Yaml, in the .github/actions folder.

We're not sure how to configure that to take the latest version rather than a specific version. The section of the yaml affected is;

```
 - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.401'
```

The following page seems to infer that we can replace the minor version with an "x" ... 

https://github.com/actions/setup-dotnet

If that's the case, the global.json could be something like this perhaps;

```
{
  "sdk": {
    "version": "3.1.200",
    "rollForward": "latestMajor"
  }
}
```

### Advantages

- Allows flexibility in which version of .NET core is present on the development machine, but will always build and deploy with the latest version.

### Acceptance Criteria

- Build and Deploy must complete successfully without specifying a specific version of .NET Core 3.1

**Comment by pjgpetecodes** [comment]
@mosoftwareenterprises... If you're interested in taking this one on... It's all yours!

**Comment by mosoftwareenterprises** [comment]
@pjgpetecodes yes I would like to take this one. Thanks

**Comment by pjgpetecodes** [comment]
Done!

**Comment by wordshaker** [comment]
Problem fixed by @mosoftwareenterprises
