### ISSUE TITLE
Hacktoberfest Bug: Sponsor Logos not adapting to different widths

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnetnotts/dotnetnotts-web#62]
### Describe the bug

The PJG Creations Sponsor Logo on the Homepage is squished.

**To Reproduce**

- Load the Homepage

**Reproduces how often:**

Every time

**Expected behaviour**

Logos should be responsive to size... Perhaps a fixed height but variable width

**Screenshots**

![image](https://user-images.githubusercontent.com/7139618/95443916-18ed3100-0955-11eb-8515-c667a1f30450.png)

**Comment by pjgpetecodes** [comment]
@rajeevbhat27... Did you want to put your hand up for this one?

**Comment by rajeevbhat27** [comment]
sure @pjgpetecodes

**Comment by pjgpetecodes** [comment]
Thanks @rajeevbhat27!

**Comment by pjgpetecodes** [comment]
Hint for this one;

```
@media (min-width: 768px)
.sponsors-logo {
    /* width: 100px; */
    height: 100px;
    margin: 20px 20px 50px;
}
```
