### ISSUE TITLE
Hacktoberfest Bug: Sponsor Logos are blocked by uBlock Origin

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnetnotts/dotnetnotts-web#63]
### Describe the bug

uBlock Origin is blocking the Sponsor Images on the Homepage.

This is caused we think by the `sponsor-logo` class on the Image.

**To Reproduce**

- Load the Homepage

**Reproduces how often:**

Every time

**Expected behaviour**

The Sponsor Logos should be shown if uBlock Origin is installed.

**Screenshots**

![image](https://user-images.githubusercontent.com/7139618/95444218-771a1400-0955-11eb-99d5-fc1998a5cde2.png)

**Comment by pjgpetecodes** [comment]
@rajeevbhat27... Did you want to put your hand up for this one?

**Comment by rajeevbhat27** [comment]
Didn't understand the issue.

**Comment by chatRG** [comment]
@pjgpetecodes I can fix this!

**Comment by pjgpetecodes** [comment]
@chatRG ... Consider it yours! @rajeevbhat27... Yeah, Chrome / Edge seem to block the `sponsor-logo` class I think?

**Comment by rajeevbhat27** [comment]
Okay..it should be fine if we change the class name i guess.

**Comment by chatRG** [comment]
@pjgpetecodes Fixed in PR #64
