### ISSUE TITLE
Hacktober Feature Request: Create Blank Page for Learn .NET Resources and Add to Nav

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#7]
### Description Of Feature

* Create Blank Page for Learn .NET Resources
* Add to Navigation Bar

### Advantages

* Page is in place to add .NET Resources

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] A blank page is added that can be navigated to from a link on the navigation bar
- [ ] Navigation has a "Learn .NET" link

**Comment by rajeevbhat27** [comment]
Hi..I would like to work on this.

**Comment by pjgpetecodes** [comment]
Okeydokey @rajeevbhat27... Thanks... Consider yourself assigned!

**Comment by rajeevbhat27** [comment]
Thanks, @pjgpetecodes  I will contribute for this in the Hactoberfest period ;)
