### ISSUE TITLE
Feature Request: Port to .NET 5

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#78]
### Describe the feature

- Port the site to .NET 5

### Advantages

- Huge performance advantages

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Site is ported to .NET 5 with no regressions to functionality

**Comment by gyro2009** [comment]
Can I get this issue please?

**Comment by wordshaker** [comment]
All yours!

**Comment by wordshaker** [comment]
Completed by @gyro2009. Thanks Paul!
