### ISSUE TITLE
Feature Request: Add information on homepage

### ISSUE THREAD

**Issue by kmlhsn** [dotnetnotts/dotnetnotts-web#80]
### Describe the feature
Add information on homepage

### Advantages
Currently there is no much information on homepage: https://dotnetnotts.co/

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ]

**Comment by wordshaker** [comment]
This repository is for the new website soon to be hosted on dotnetnotts.co.uk

The old website will later be removed.
